### ISSUE TITLE
Crash on null object reference

### ISSUE THREAD

**Issue by DougSteiert** [DougSteiert/ResearchApp#4]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'io.realm.RealmList com.djsg38.locationprivacyapp.models.Session.getRealLocations()' on a null object reference
                                                                                 at com.djsg38.locationprivacyapp.MainActivity$4.execute(MainActivity.java:151)
                                                                                 at io.realm.Realm.executeTransaction(Realm.java:1254)
                                                                                 at com.djsg38.locationprivacyapp.MainActivity.onCreate(MainActivity.java:143)

**Comment by user404d** [comment]
Fixed as far as I can tell. The issue was tempLoc being set to null and never initialized as a Location of any kind. The fix was to set it to a Location. I also made some other small changes. [See changes here.](https://github.com/DougSteiert/ResearchApp/commit/53f3f8052cacb75e3a7fa6b86a5fbfd0fd1863e5) Almost forgot to push this up.
